### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by wukongtea** [qwIvan/dotfiles#1]
希望你可以自己做一个项目。

**Comment by wukongtea** [comment]
大神有没有博客什么的联系方式，能不能介绍下 你是怎么得到 生成方法的呢？

**Comment by wukongtea** [comment]
https://v.qq.com/x/cover/dn2mnt7dnlnf4o6.html  我试了下，好像解析失败啊？

**Comment by qwIvan** [comment]
@wukongtea 试了一下，解析没问题

**Comment by qwIvan** [comment]
@wukongtea 你有没有切换到qq_reimpl这个分支
git checkout qq_reimple

**Comment by wukongtea** [comment]
谢谢了，我pip3  把原来版本删除了 重新装了一下 就好了，不过网上的TX的一些无水印的接口不知道是什么，大神有办法么？

**Comment by wukongtea** [comment]
您的邮箱是多少啊？

**Comment by qwIvan** [comment]
@wukongtea 哪里有无水印的接口吗？

**Comment by wukongtea** [comment]
![image](https://cloud.githubusercontent.com/assets/25115961/23114241/e4be570c-f778-11e6-8bb0-8033ff862178.png)
你用html5端口 试试看吧。

**Comment by qwIvan** [comment]
@wukongtea 
h5vv无法得到1080P。
测试视频：https://v.qq.com/x/cover/r57z3fzzgi0owl3.html

**Comment by wukongtea** [comment]
接口虽然不同，别的接口1080P算法应该通用的吧，上面的代码应该只是计算720P的吧。
你可以参考http://www.jianshu.com/p/eae2b7077e04 这篇文章，就抓到了1080P。

**Comment by wukongtea** [comment]
iqiyi的1080P vip视频有办法得到么,可以对you-get 改进一下么？
